# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52abbb601b3efc1b46fcc4820b2091936040cf5c86eb744ce38f3b19e2405df98bf5ab287d58f0272ad1b654b6cd76773341621527942e123b4935b9dd13631f

test:
  secret_key_base: d3f2d062bd1d8455dbd4ce1137483a160ebdd9e4cc0f79ad71b534da34f4069e6c6377bb88aaff0db62222882ab5cd065acff620a67919f61dddcb6c9a5d188e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
